create extension if not exists pgcrypto;

create table if not exists app_users (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  created_at timestamptz not null default now(),
  constraint app_users_name_email_unique unique (name, email)
);

create table if not exists materials (
  id bigint generated by default as identity primary key,
  name text not null unique,
  quantity numeric not null default 0,
  unit text not null default 'unit',
  low_stock_threshold numeric not null default 10,
  created_at timestamptz not null default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  product_name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists product_ingredients (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  material_name text not null,
  amount_per_unit numeric not null check (amount_per_unit > 0)
);

create table if not exists finished_goods (
  product_id bigint primary key references products(id) on delete cascade,
  product_name text not null,
  quantity numeric not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists production_logs (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete set null,
  product_name text not null,
  quantity numeric not null,
  material_summary jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table app_users enable row level security;
alter table materials enable row level security;
alter table products enable row level security;
alter table product_ingredients enable row level security;
alter table finished_goods enable row level security;
alter table production_logs enable row level security;

create policy if not exists "Allow anon full app_users"
  on app_users for all
  using (true)
  with check (true);

create policy if not exists "Allow anon full materials"
  on materials for all
  using (true)
  with check (true);

create policy if not exists "Allow anon full products"
  on products for all
  using (true)
  with check (true);

create policy if not exists "Allow anon full product_ingredients"
  on product_ingredients for all
  using (true)
  with check (true);

create policy if not exists "Allow anon full finished_goods"
  on finished_goods for all
  using (true)
  with check (true);

create policy if not exists "Allow anon full production_logs"
  on production_logs for all
  using (true)
  with check (true);
