create extension if not exists pgcrypto;

create table if not exists app_users (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  first_name text,
  last_name text,
  name text not null,
  email text not null unique,
  country text,
  created_at timestamptz not null default now(),
  constraint app_users_name_unique unique (name)
);

create table if not exists materials (
  id bigint generated by default as identity primary key,
  name text not null unique,
  quantity numeric not null default 0,
  unit text not null default 'unit',
  cost_price numeric not null default 0,
  cost_currency text not null default 'USD',
  low_stock_threshold numeric not null default 10,
  purchase_date date not null default current_date,
  created_at timestamptz not null default now()
);

alter table materials
  add column if not exists cost_price numeric not null default 0;

alter table materials
  add column if not exists cost_currency text not null default 'USD';

alter table materials
  add column if not exists purchase_date date not null default current_date;

create table if not exists products (
  id bigint generated by default as identity primary key,
  product_name text not null unique,
  unit_currency text not null default 'USD',
  unit_price numeric not null default 0,
  created_at timestamptz not null default now()
);

alter table products
  add column if not exists unit_price numeric not null default 0;

alter table products
  add column if not exists unit_currency text not null default 'USD';

create table if not exists product_ingredients (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  material_name text not null,
  amount_per_unit numeric not null check (amount_per_unit > 0)
);

create table if not exists finished_goods (
  product_id bigint primary key references products(id) on delete cascade,
  product_name text not null,
  quantity numeric not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists production_logs (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete set null,
  product_name text not null,
  quantity numeric not null,
  material_summary jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists sales (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete set null,
  product_name text not null,
  quantity_sold numeric not null check (quantity_sold > 0),
  unit_currency text not null default 'USD',
  unit_price numeric not null default 0,
  total_amount numeric not null default 0,
  quantity_left numeric not null default 0,
  sale_date date not null default current_date,
  created_at timestamptz not null default now()
);

alter table app_users enable row level security;
alter table materials enable row level security;
alter table products enable row level security;
alter table product_ingredients enable row level security;
alter table finished_goods enable row level security;
alter table production_logs enable row level security;
alter table sales enable row level security;

drop policy if exists "Allow anon full app_users" on app_users;
drop policy if exists "Allow anon full materials" on materials;
drop policy if exists "Allow anon full products" on products;
drop policy if exists "Allow anon full product_ingredients" on product_ingredients;
drop policy if exists "Allow anon full finished_goods" on finished_goods;
drop policy if exists "Allow anon full production_logs" on production_logs;
drop policy if exists "Allow anon full sales" on sales;

create policy "Users can view own profile"
  on app_users for select
  using (auth.uid() = auth_user_id);

create policy "Users can insert own profile"
  on app_users for insert
  with check (auth.uid() = auth_user_id);

create policy "Users can update own profile"
  on app_users for update
  using (auth.uid() = auth_user_id)
  with check (auth.uid() = auth_user_id);

create policy "Authenticated full materials"
  on materials for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "Authenticated full products"
  on products for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "Authenticated full product_ingredients"
  on product_ingredients for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "Authenticated full finished_goods"
  on finished_goods for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "Authenticated full production_logs"
  on production_logs for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "Authenticated full sales"
  on sales for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');